### PR TITLE
Report errors on the table creation to the user

### LINKED ISSUE #980: [Bug]: formula-list-selectors arguments make tm_gtsummary to fail
### What happened?

Passing some formula-list-selectors arguments makes the module to silently fail:

```r
library("teal.modules.general")
data <- within(teal.data::teal_data(), {
  ADSL <- teal.data::rADSL
})
join_keys(data) <- default_cdisc_join_keys[names(data)]
app <- init(
  data = data,
  modules = modules(
    tm_gtsummary(
      by = teal.transform::data_extract_spec(
        dataname = "ADSL",
        select = teal.transform::select_spec(
          choices = c("SEX", "COUNTRY", "SITEID", "ACTARM"),
          selected = "SEX",
          multiple = FALSE
        )
      ),
      include = teal.transform::data_extract_spec(
        dataname = "ADSL",
        select = teal.transform::select_spec(
          choices = c("SITEID", "COUNTRY", "ACTARM"),
          selected = "SITEID",
          multiple = TRUE,
          fixed = FALSE
        )
      ),
      statistic = all_continuous() ~ "{median} ({p75})",
      type = everything() ~ "continuous2"
    )
  )
)
if (interactive()) {
  shinyApp(app$ui, app$server)
}
```

We'll need to defuse each argument and generate the call with the right information. 

### sessionInfo()

```R

```

### Relevant log output

```R

```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [x] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [x] I agree to follow this project's Security Policy.

### PR DESCRIPTION
**Pull request by llrs-roche**
# Pull Request

Fixes #980 

Errors are shown to the user:

image

Previously no information was provided

<details>
<summary>Details</summary>

```r
data <- within(teal.data::teal_data(), {
  ADSL <- teal.data::rADSL
})
join_keys(data) <- default_cdisc_join_keys[names(data)]
app <- init(
  data = data,
  modules = modules(
    tm_gtsummary(
      by = teal.transform::data_extract_spec(
        dataname = "ADSL",
        select = teal.transform::select_spec(
          choices = c("SEX", "COUNTRY", "SITEID", "ACTARM"),
          selected = "SEX",
          multiple = FALSE
        )
      ),
      include = teal.transform::data_extract_spec(
        dataname = "ADSL",
        select = teal.transform::select_spec(
          choices = c("SITEID", "COUNTRY", "ACTARM"),
          selected = "SITEID",
          multiple = TRUE,
          fixed = FALSE
        )
      ),
      type = everything() ~ "continuous2"
    )
  )
) |> runApp()
```

</details>

### CODE REVIEW

File: R/tm_gtsummary.R [hunk 1]
```diff
@@ -266,34 +264,26 @@ srv_gtsummary <- function(id,
         },
         table_crane = table_call
       )
+
+      validate(need(!isa(qq, "qenv.error"), if (isa(qq, "qenv.error")) as.character(qq)))
```
Comment (gogonzo) [inline R/tm_gtsummary.R]: Is it needed? `srv_transform_teal_data` handles errors from previous stages

Comment (gogonzo) [reply R/tm_gtsummary.R]: But you're already using this via `srv_decorate_teal_data`. Or am I missing something?

**Review by gogonzo — APPROVED** [review]
👍
