### PR TITLE
Fix missing attached packages

### LINKED ISSUE #786: [Bug]: modules crash if package not attached
### What happened?

Unless the package is attached, at least some modules fail.
THIS IS A TWO-PART ISSUE

### PART 1

`teal.modules.general` seems to rely on the `magrittr` pipe but does not re-export it.
```
teal_app <- teal::init(
  data = teal.data::teal_data(ADSL = teal.modules.general::rADSL),
  modules = teal::modules(teal.modules.general::tm_missing_data())
)
shiny::runApp(teal_app)
```
image

I suggest re-exporting the pipe operator OR replacing it with the native pipe.
_Be careful with native pipe, it changes how the call looks like:_

```r
quote(a |> foo() |> foo2())
# foo2(foo(a))
```

### PART 2

`tm_missing_data` (and possibly other modules) requires `ggplot2` to be attached (`ggplot` function used without prefix) but does not enforce attaching, unless it is itself attached.

```
library(magrittr)
teal_app <- teal::init(
  data = teal.data::teal_data(ADSL = teal.modules.general::rADSL),
  modules = teal::modules(teal.modules.general::tm_missing_data())
)
shiny::runApp(teal_app)
```

image

### sessionInfo()

_No response_

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

### PR DESCRIPTION
**Pull request by llrs-roche**
# Pull Request

Fixes #786

This PR load the packages needed before the code is evaluated inside the qenv.
This makes the modules' code more reproducible and solve these errors:

image

We (@m7pr  + me) decided to still add the prefixes on functions to avoid namespace conflicts.

### CODE REVIEW

**Comment by m7pr** [comment]
This change fixes #786 + adds direct library calls, so that `Show R Code` panel actually includes them.
So the code from `Show R Code` was not reproducible before.

We decided to pay attention to prefixes, to avoid name conflicts. Hovewer we decided not to prefix operators `+` and `%>%` - those need direct library(package) call. magrittr is not used as we import pipe from dplyr.

File: R/tm_missing_data.R [hunk 1]
```diff
@@ -535,18 +535,21 @@ srv_missing_data <- function(id,
 
       group_var <- input$group_by_var
       anl <- data_r()
+      qenv <- teal.code::eval_code(data(), {
+        "library('dplyr');library('ggplot2');library('tidyr');library('forcats');library('glue')"
+      })
```
Comment (m7pr) [inline R/tm_missing_data.R:540]: Maybe change to 
```r
substitute(
   expr = {
       library(dplyr)
       library(ggplot2)
       ....
   }
)

```

Comment (llrs-roche) [reply R/tm_missing_data.R:540]: If I apply this change I see a warning while checking it:

```
W  checking dependencies in R code (2.9s)
   'library' or 'require' calls not declared from:
     'dplyr' 'forcats' 'glue' 'sparkline' 'tidyr'
   'library' or 'require' call to 'ggplot2' which was already attached by Depends.
     Please remove these calls from your code.
   'library' or 'require' calls in package code:
     'dplyr' 'forcats' 'glue' 'sparkline' 'tidyr'
     Please use :: or requireNamespace() instead.
     See section 'Suggested packages' in the 'Writing R Extensions' manual.
```

We know that this code is safe and it is not evaluated but I think it will be harder to sell that to CRAN

Comment (m7pr) [reply R/tm_missing_data.R:540]: oh yes, let's don't use substitute in this case : ) closing the conversation

File: R/tm_missing_data.R [hunk 2]
```diff
@@ -535,18 +535,21 @@ srv_missing_data <- function(id,
 
       group_var <- input$group_by_var
       anl <- data_r()
+      qenv <- teal.code::eval_code(data(), {
+        "library('dplyr');library('ggplot2');library('tidyr');library('forcats');library('glue')"
```
Comment (pawelru) [inline R/tm_missing_data.R:539]: can we change `'` into `"` so that we follow the convention that all the strings are in double quoutes?

Comment (llrs-roche) [reply R/tm_missing_data.R:539]: Sure, I can change to 'library("dplyr");...'

Comment (llrs-roche) [reply R/tm_missing_data.R]: Resolved on [27611dd](https://github.com/insightsengineering/teal.modules.general/pull/847/commits/27611dd05cefb2ddb140644545bc8061d808db99)

**Comment by llrs-roche** [comment]
I think it is ready for review, I'll fix the SuperLinter issues with the review comments.

File: DESCRIPTION [hunk 3]
```diff
@@ -58,6 +58,7 @@ Imports:
     sparkline (>= 2.0),
     stats,
     stringr (>= 1.4.1),
+    styler,
```
Comment (m7pr) [inline DESCRIPTION:61]:
```suggestion
    styler (>= 1.10.3),
```

File: NEWS.md [hunk 4]
```diff
@@ -3,6 +3,7 @@
 * Removed `Show Warnings` modals from modules.
 * Soft deprecated `datasets_selected` argument of modules in favor of `datanames`.
 * Soft deprecated `show_metadata` argument of `tm_front_page()` in favor of `datanames`.
+* Module's code include library calls and is styled before presenting it to the users.
```
Comment (m7pr) [inline NEWS.md:6]:
```suggestion
* Modules' Show R Code widgets include library calls and their code is styled with `styler` package.
```

**Comment by m7pr** [comment]
hey @llrs-roche , really great job with the modules on tmg! I will review each module separately! it might take some time : )

In the meantime, can you have a look at the SuperLinter fail?

File: DESCRIPTION (hunk 3 above)
Comment (llrs-roche) [reply DESCRIPTION:61]: I thought about this and this would require people to use the latest version and seeing the challenges to validate the package I decided against it. But I will add it now.

File: R/tm_a_pca.R [hunk 5]
```diff
@@ -438,10 +438,10 @@ srv_a_pca <- function(id, data, reporter, filter_panel_api, dat, plot_height, pl
       selector_list = selector_list,
       datasets = data
     )
-
+    qenv <- teal.code::eval_code(data(), 'library("ggplot2")')
```
Comment (m7pr) [inline R/tm_a_pca.R:441]: Do we need `dplyr` and `tidyr` in `tm_a_pca`? Check out the `Show R Code`, it has some `dplyr` operations and `%>%`
```suggestion
    qenv <- teal.code::eval_code(data(), 'library("ggplot2");library("dplyr");library("tidyr")') # nolint quotes
```

Also added `# nolint` because you used `'` quotes for strings

image

File: R/tm_a_regression.R [hunk 6]
```diff
@@ -448,9 +448,14 @@ srv_a_regression <- function(id,
       )
     })
 
+    qenv <- teal.code::eval_code(
+      data(),
+      "library('ggplot2');"
```
Comment (m7pr) [inline R/tm_a_regression.R:453]: With Pawel suggestion libraries should have `"` inside
```suggestion
      'library("ggplot2")' # nolint quotes
```

File: R/tm_data_table.R [hunk 7]
```diff
@@ -318,9 +318,12 @@ srv_data_table <- function(id,
       df <- data()[[dataname]]
 
       teal::validate_has_data(df, min_nrow = 1L, msg = paste("data", dataname, "is empty"))
-
-      teal.code::eval_code(
+      qenv <- teal.code::eval_code(
         data(),
+        'library("ggplot2");library("dplyr");library("DT")'
+      )
```
Comment (m7pr) [inline R/tm_data_table.R:324]: Do you think we should somehow expose Show R Code in `tm_data_table`?

File: R/tm_data_table.R [hunk 8]
```diff
@@ -318,9 +318,12 @@ srv_data_table <- function(id,
       df <- data()[[dataname]]
 
       teal::validate_has_data(df, min_nrow = 1L, msg = paste("data", dataname, "is empty"))
-
-      teal.code::eval_code(
+      qenv <- teal.code::eval_code(
         data(),
+        'library("ggplot2");library("dplyr");library("DT")'
```
Comment (m7pr) [inline R/tm_data_table.R:323]: I don't think there is `ggplot2` in DT : P
```suggestion
        'library("dplyr");library("DT")'
```

File: R/tm_g_association.R [hunk 9]
```diff
@@ -330,9 +330,13 @@ srv_tm_g_association <- function(id,
       selector_list = selector_list
     )
 
+    qenv <- teal.code::eval_code(
+      data(),
+      'library("ggplot2");library("dplyr")'
```
Comment (m7pr) [inline R/tm_g_association.R:335]: This plot is based on `tm_g_bivariate` and use functions from another file
```suggestion
      'library("ggplot2");library("dplyr");library("tern");library("ggmosaic");library("grid")'
```

image

File: R/tm_g_bivariate.R [hunk 10]
```diff
@@ -535,10 +535,14 @@ srv_g_bivariate <- function(id,
       selector_list = selector_list,
       datasets = data
     )
+    qenv <- teal.code::eval_code(
+      data(),
+      'library("ggplot2");library("dplyr")'
+    )
```
Comment (m7pr) [inline R/tm_g_bivariate.R:541]: Can you open an issue to fix default example in `tm_g_bivariate`? It produces empty results
image


```r
# general data example
data <- teal_data()
data <- within(data, {
  require(nestcolor)
  CO2 <- data.frame(CO2)
})

app <- init(
  data = data,
  modules = tm_g_bivariate(
    x = data_extract_spec(
      dataname = "CO2",
      select = select_spec(
        label = "Select variable:",
        choices = variable_choices(data[["CO2"]]),
        selected = "conc",
        fixed = FALSE
      )
    ),
    y = data_extract_spec(
      dataname = "CO2",
      select = select_spec(
        label = "Select variable:",
        choices = variable_choices(data[["CO2"]]),
        selected = "uptake",
        multiple = FALSE,
        fixed = FALSE
      )
    ),
    row_facet = data_extract_spec(
      dataname = "CO2",
      select = select_spec(
        label = "Select variable:",
        choices = variable_choices(data[["CO2"]]),
        selected = "Type",
        fixed = FALSE
      )
    ),
    col_facet = data_extract_spec(
      dataname = "CO2",
      select = select_spec(
        label = "Select variable:",
        choices = variable_choices(data[["CO2"]]),
        selected = "Treatment",
        fixed = FALSE
      )
    )
  )
)
if (interactive()) {
  shinyApp(app$ui, app$server)
}

```

File: R/tm_g_bivariate.R [hunk 11]
```diff
@@ -535,10 +535,14 @@ srv_g_bivariate <- function(id,
       selector_list = selector_list,
       datasets = data
     )
+    qenv <- teal.code::eval_code(
+      data(),
+      'library("ggplot2");library("dplyr")'
```
Comment (m7pr) [inline R/tm_g_bivariate.R:540]: The same as in `tm_g_association`, but there might be more once the module is fixed, and you can see the actual code.
```suggestion
      'library("ggplot2");library("dplyr");library("tern");library("ggmosaic");library("grid")' # nolint quotes
```

File: R/tm_g_distribution.R [hunk 12]
```diff
@@ -542,9 +542,14 @@ srv_distribution <- function(id,
       datasets = data
     )
 
+    qenv <- teal.code::eval_code(
+      data(),
+      'library("ggplot2");library("forcats");library("dplyr")'
```
Comment (m7pr) [inline R/tm_g_distribution.R:547]: There is no `forcats` but there is `rlistings` in the default example from the module

image


```suggestion
      'library("ggplot2");library("rlistings");library("dplyr")'
```

`forcats` is added only under 2 circumnstanes under those 2 `if` statements.
Maybe you can extend the `qenv` there with a `library(forcats)` call

image

File: R/tm_g_scatterplot.R [hunk 13]
```diff
@@ -574,10 +574,11 @@ srv_g_scatterplot <- function(id,
       datasets = data,
       merge_function = "dplyr::inner_join"
     )
+    qenv <- teal.code::eval_code(data(), 'library("ggplot2");library("dplyr")')
```
Comment (m7pr) [inline R/tm_g_scatterplot.R:577]:
```suggestion
    qenv <- teal.code::eval_code(data(), 'library("ggplot2");library("dplyr")') # nolint quotes
```

File: R/tm_g_scatterplotmatrix.R [hunk 14]
```diff
@@ -483,7 +483,7 @@ srv_g_scatterplotmatrix <- function(id,
     })
 
     # Render R code.
-    source_code_r <- reactive(teal.code::get_code(req(decorated_output_q())))
+    source_code_r <- reactive(prepare_code(decorated_output_q()))
```
Comment (m7pr) [inline R/tm_g_scatterplotmatrix.R:486]: @llrs-roche I think you missed libraries at `tm_g_sctterplotmatrix`.
`lattice` and `dplyr`

image

File: R/tm_missing_data.R [hunk 15]
```diff
@@ -890,32 +893,32 @@ srv_missing_data <- function(id,
...
+              ggplot2::geom_text(
+                ggplot2::aes(label = ifelse(isna == TRUE, sprintf("%d [%.02f%%]", n, n_pct), ""), y = 1),
                 hjust = 1,
                 color = "black"
               ) +
               labs +
               ggthemes +
               themes +
-              coord_flip(),
+              ggplot2::coord_flip(),
```
Comment (m7pr) [inline R/tm_missing_data.R:921]: look lines below `ggplotGrob` is not prefixed

File: R/tm_missing_data.R [hunk 16]
```diff
@@ -535,18 +535,21 @@ srv_missing_data <- function(id,
 
       group_var <- input$group_by_var
       anl <- data_r()
+      qenv <- teal.code::eval_code(data(), {
+        'library("dplyr");library("ggplot2");library("tidyr");library("forcats");library("glue")'
```
Comment (m7pr) [inline R/tm_missing_data.R:539]: `forcats` and `glue` are not used always.
`ggplotGrob` is not prefixed.
`grid` is not loaded

using default example from module

image

File: R/tm_outliers.R [hunk 17]
```diff
@@ -1304,7 +1307,7 @@ srv_outliers <- function(id, data, reporter, filter_panel_api, outlier_var,
     })
 
     # Render R code.
-    source_code_r <- reactive(teal.code::get_code(req(decorated_final_q())))
+    source_code_r <- reactive(prepare_code(decorated_final_q()))
```
Comment (m7pr) [inline R/tm_outliers.R:1310]: library calls are omitted in `tm_outliers` for all packages. please add

No `library()` calls in the module's example code

image

File: R/tm_t_crosstable.R [hunk 18]
```diff
@@ -300,10 +300,10 @@ srv_t_crosstable <- function(id, data, reporter, filter_panel_api, label, x, y,
       selector_list = selector_list,
       merge_function = merge_function
     )
-
+    qenv <- teal.code::eval_code(data(), 'library("rtables");')
```
Comment (m7pr) [inline R/tm_t_crosstable.R:303]:
```suggestion
    qenv <- teal.code::eval_code(data(), 'library("rtables")') # nolint quotes
```

File: R/tm_variable_browser.R [hunk 19]
```diff
@@ -779,8 +779,8 @@ plot_var_summary <- function(var,
   } else if (inherits(var, "Date") || inherits(var, "POSIXct") || inherits(var, "POSIXlt")) {
     var_num <- as.numeric(var)
     binwidth <- get_bin_width(var_num, 1)
-    p <- ggplot(data = data.frame(var = var), aes(x = var, y = after_stat(count))) +
-      geom_histogram(binwidth = binwidth)
+    p <- ggplot2::ggplot(data = data.frame(var = var), ggplot2::aes(x = var, y = ggplot2::after_stat(count))) +
+      ggplot2::geom_histogram(binwidth = binwidth)
```
Comment (m7pr) [inline R/tm_variable_browser.R:783]: below `ggplotGrob` is not prefixed

File: R/tm_variable_browser.R [hunk 20]
```diff
@@ -713,11 +713,11 @@ plot_var_summary <- function(var,
         var <- stringr::str_wrap(var, width = wrap_character)
       }
       var <- if (isTRUE(remove_NA_hist)) as.vector(stats::na.omit(var)) else var
-      ggplot(data.frame(var), aes(x = forcats::fct_infreq(as.factor(var)))) +
-        geom_bar(
+      ggplot2::ggplot(data.frame(var), ggplot2::aes(x = forcats::fct_infreq(as.factor(var)))) +
```
[the remark this answers is not in the document]
Comment (m7pr) [reply R/tm_variable_browser.R:716]: ah ok, there is no `qenv` at all and no `eval.code` in this module

File: R/tm_data_table.R (hunk 7 above)
Comment (llrs-roche) [reply R/tm_data_table.R:324]: I think is one of the few that don't have it. But I am not sure why it doesn't and how it would be used. The description says: "It uses the DT package to display data tables in a paginated, searchable, and sortable format, which helps to enhance data exploration and analysis." For doing this interactively usually `View` works better, the only advantage is the paginated output...

File: R/tm_g_association.R (hunk 9 above)
Comment (llrs-roche) [reply R/tm_g_association.R:347]: Good catch, I think I thought that prefixing would be enough on this case. But I also see an aes without `ggplot2::`

File: R/tm_g_bivariate.R (hunk 10 above)
Comment (llrs-roche) [reply R/tm_g_bivariate.R:553]: Sure!

File: R/tm_g_response.R [hunk 21]
```diff
@@ -378,9 +378,14 @@ srv_g_response <- function(id,
       datasets = data
     )
 
+    qenv <- teal.code::eval_code(
+      data(),
+      'library("ggplot2");library("dplyr");library("forcats")'
```
[the remark this answers is not in the document]
Comment (llrs-roche) [reply R/tm_g_response.R:395]: I'll add it depending on which path the code follows, but I am not sure it is possible to add it to the beginning of the code at that point. We'll see

File: R/tm_variable_browser.R (hunk 19 above)
Comment (llrs-roche) [reply R/tm_variable_browser.R:783]: I'll check that . Thanks

**Review by llrs-roche — COMMENTED** [review]
Many thanks for the detailed review @m7pr! I'll work on all the feedback provided.

File: R/tm_g_bivariate.R (hunk 10 above)
Comment (llrs-roche) [reply R/tm_g_bivariate.R:553]: Opened here: https://github.com/insightsengineering/teal.modules.general/issues/852

File: R/tm_g_distribution.R (hunk 12 above)
Comment (llrs-roche) [reply R/tm_g_distribution.R]: forcats added on these two conditions, also added generics in once other code branch.

**Review by llrs-roche — COMMENTED** [review]
Addressing the remaining comments. 
I also found some other calls missing a prefix.

File: R/tm_g_bivariate.R (hunk 10 above)
Comment (llrs-roche) [reply R/tm_g_bivariate.R:553]: Sorry, this is an error I introduced by replacing `call("facet_grid", ...` with `call("ggplot2::facet_grid", ...). I'm investigating now if I can have the prefix and add use call inside qenv.

File: R/tm_missing_data.R (hunk 16 above)
Comment (m7pr) [reply R/tm_missing_data.R]: amazing, ok

File: R/tm_g_bivariate.R (hunk 10 above)
Comment (m7pr) [reply R/tm_g_bivariate.R:553]: ok

File: R/tm_data_table.R (hunk 7 above)
Comment (m7pr) [reply R/tm_data_table.R]: after seconds thoughts I think it's not worth it

File: R/tm_g_association.R [hunk 22]
```diff
@@ -500,7 +504,7 @@ srv_tm_g_association <- function(id,
             expr = {
               plot_top <- plot_calls[[1]]
               plot_bottom <- plot_calls[[1]]
-              plot <- tern::stack_grobs(grobs = lapply(list(plot_top, plot_bottom), ggplotGrob))
+              plot <- tern::stack_grobs(grobs = lapply(list(plot_top, plot_bottom), ggplot2::ggplotGrob))
```
Comment (m7pr) [inline R/tm_g_association.R:507]: In lines above this we have

```r
              plot_top <- plot_calls[[1]]
              plot_bottom <- plot_calls[[1]]
```

and the corresponding output code is (in Show R Code)

image


Should it actually be

```r
              plot_top <- plot_calls[[1]]
              plot_bottom <- plot_calls[[2]]
```

?

Comment (m7pr) [reply R/tm_g_association.R]: There was also very weird code output. I changed it so there is only one creation of plots
d6ea33a36a81d2979a8bf8c0380885ff59037d61
image

File: R/tm_g_bivariate.R (hunk 10 above)
Comment (m7pr) [reply R/tm_g_bivariate.R:553]: so it's gonna be `facet_grid` without prefixes?

File: R/tm_g_scatterplotmatrix.R [hunk 23]
```diff
@@ -329,8 +329,8 @@ srv_g_scatterplotmatrix <- function(id,
 
     anl_merged_q <- reactive({
       req(anl_merged_input())
-      data() %>%
-        teal.code::eval_code(as.expression(anl_merged_input()$expr))
+      qenv <- teal.code::eval_code(data(), 'library("dplyr");library("lattice")') # nolint quotes
```
Comment (m7pr) [inline R/tm_g_scatterplotmatrix.R:332]: I think there is something before that uses dplyr, so maybe let's attach packages there?

image

Comment (llrs-roche) [reply R/tm_g_scatterplotmatrix.R:332]: AFAIK, this is the first call to `data()`/`eval_code()` inside server. If this is modified somewhere else I think this would mean to update all modules.

File: R/utils.R [hunk 24]
```diff
@@ -399,3 +399,9 @@ select_decorators <- function(decorators, scope) {
     list()
   }
 }
+
+
+prepare_code <- function(x) {
+  code <- teal.code::get_code(req(x))
+  paste(as.character(styler::style_text(code)), collapse = "\n")
+}
```
Comment (gogonzo) [inline R/utils.R:407]: No styler before the release. Show R code might disappear completely from the modules soon 
```suggestion
prepare_code <- function(x) {
  code <- teal.code::get_code(req(x))
  paste(as.character(styler::style_text(code)), collapse = "\n")
}
```

Comment (m7pr) [reply R/utils.R:407]: @llrs-roche if that's the case, let's revert this, and let's open new issue to discuss.

Comment (llrs-roche) [reply R/utils.R]: Done! reverted on [3481365](https://github.com/insightsengineering/teal.modules.general/pull/847/commits/34813656c849928368bf1859e515d3f98a9d4621), issue opened at #853

File: R/tm_g_scatterplotmatrix.R (hunk 23 above)
Comment (llrs-roche) [reply R/tm_g_scatterplotmatrix.R:332]: This is generated by `join_keys` from the example. If I don't join_keys on the data I see this code:
image
I wouldn't go to modify how join_keys are handled.

Comment (gogonzo) [reply R/tm_g_scatterplotmatrix.R:332]: `inner_join` comes from filter panel. I don't recommend to change it there.

**Review by m7pr — APPROVED** [review]

File: R/tm_g_scatterplotmatrix.R (hunk 23 above)
Comment (m7pr) [reply R/tm_g_scatterplotmatrix.R:332]: Alrighty, it is how it is

File: R/utils.R [hunk 25]
```diff
@@ -399,3 +399,8 @@ select_decorators <- function(decorators, scope) {
     list()
   }
 }
+
+
+prepare_code <- function(x) {
+  teal.code::get_code(req(x))
+}
```
[the remark this answers is not in the document]
Comment (llrs-roche) [reply R/utils.R]: Sure, done on 22427b137b6aa4fd060c4eb3f3554deb3c50f69b

File: R/tm_g_bivariate.R (hunk 10 above)
Comment (llrs-roche) [reply R/tm_g_bivariate.R:553]: Any opinion on this @m7pr ? Do I resolve this and merge or open a separate issue?
