### PR TITLE
29 add non-cdisc examples to the modules

### LINKED ISSUE #29: Add non-cdisc examples to the modules
Modules without a non-cdisc example:
* [x] tm_a_pca
* [x] tm_a_regression _bug detected (BLOCKER!)_ https://github.com/insightsengineering/teal.slice/issues/560
* [x] tm_data_table
* [x] tm_g_association _bug detected_ https://github.com/insightsengineering/teal.modules.general/issues/645
* [x] tm_g_bivariate
* [x] tm_g_response
* [x] tm_g_scatterplot
* [x] tm_g_scatterplotmatrix
* [x] tm_missing_data
* [x] tm_outliers _bugs detected_ https://github.com/insightsengineering/teal.modules.general/issues/648, https://github.com/insightsengineering/teal.modules.general/issues/650
* [x] tm_t_crosstable _bug detected_ https://github.com/insightsengineering/teal.modules.general/issues/649
* [x] tm_variable_browser

Provenance: 
```
Creator: kpagacz
```

### PR DESCRIPTION
**Pull request by chlebowa**
Closes #29 

Added general data examples to modules.

### CODE REVIEW

File: R/tm_a_pca.R [hunk 1]
```diff
@@ -18,45 +18,84 @@
...
+#'   shinyApp(app$ui, app$server)
+#' }
+#'
+#' # CDISC data example
+#' library(teal.widgets)
 #'
 #' data <- teal_data()
 #' data <- within(data, {
 #'   library(nestcolor)
-#'   ADSL <- teal.modules.general::rADSL
```
Comment (m7pr) [inline R/tm_a_pca.R:30]: hi @chlebowa I know that we try to strive from prefixes in examples. The main reason I put prefixes before data name in examples was that `rADSL` exists in `teal.transform` and some other teal. packages (can't recall which others now, but `teal.transform` for sure). And the prefix is in here so that to make sure you use `rADSL` from `teal.modules.general` and not from other package, if you attached other package after you attached `teal.modules.general`.

File: R/tm_a_regression.R [hunk 2]
```diff
@@ -28,47 +28,90 @@
...
-#' # Regression graphs from selected response variable (BMRKR1) and
-#' # selected regressors (AGE)
+#' # general data example
+#' library(teal.widgets)
 #'
 #' data <- teal_data()
 #' data <- within(data, {
 #'   library(nestcolor)
-#'   ADSL <- teal.modules.general::rADSL
+#'   CO2 <- CO2
```
Comment (m7pr) [inline R/tm_a_regression.R:39]: @chlebowa if there is a way to remove `teal.modules.general::rADSL` complitely from examples, then we can maybe remove this whole dataset at all?

Comment (m7pr) [reply R/tm_a_regression.R:39]: remove this whole dataset at all from the package*?

Comment (chlebowa) [reply R/tm_a_regression.R:39]: https://github.com/insightsengineering/teal.modules.general/issues/29#issuecomment-1952358103

**Comment by m7pr** [comment]
I think this change should be merged before https://github.com/insightsengineering/teal.modules.general/pull/646 and before we start doing that for other functions

File: R/tm_a_pca.R (hunk 1 above)
Comment (chlebowa) [reply R/tm_a_pca.R:30]: 1. Are `rADSL` objects in other packages different or are they the same object exported from multiple packages?
2. When running an example, `teal.modules.general` will presumably attached last.Specifically, it is impossible to have `teal.transform` attached before `teal.modules.general` because the latter `Depends` on the former.

File: R/tm_a_regression.R (hunk 2 above)
Comment (m7pr) [reply R/tm_a_regression.R:39]: :)

File: R/tm_a_pca.R (hunk 1 above)
Comment (m7pr) [reply R/tm_a_pca.R:30]: You can resolve, once you are done reading my lengthy reply :P

**Comment by m7pr** [comment]
Hey, for `tm_a_regression` example I get

```r
Listening on http://127.0.0.1:5893
[INFO] 2024-02-21 14:38:19.6924 pid:8636 token:[040e5d95] teal Initializing reporter_previewer_module
Warning: Error in super$initialize: Assertion on 'label' failed: Must be of type 'character' (or 'NULL'), not 'list'.
  3: runApp
  2: print.shiny.appobj
  1: <Anonymous>
```

Example code

```r
# general data example
library(teal.widgets)

data <- teal_data()
data <- within(data, {
  library(nestcolor)
  CO2 <- CO2
})
datanames(data) <- c("CO2")

app <- init(
  data = data,
  modules = modules(
    tm_a_regression(
      label = "Regression",
      response = data_extract_spec(
        dataname = "CO2",
        select = select_spec(
          label = "Select variable:",
          choices = "uptake",
          selected = "uptake",
          multiple = FALSE,
          fixed = TRUE
        )
      ),
      regressor = data_extract_spec(
        dataname = "CO2",
        select = select_spec(
          label = "Select variables:",
          choices = variable_choices(data[["CO2"]], c("conc", "Treatment")),
          selected = "conc",
          multiple = TRUE,
          fixed = FALSE
        )
      ),
      ggplot2_args = ggplot2_args(
        labs = list(subtitle = "Plot generated by Regression Module")
      )
    )
  )
)
if (interactive()) {
  shinyApp(app$ui, app$server)
}

```

**Comment by chlebowa** [comment]
@m7pr update your `teal.slice`.

**Comment by m7pr** [comment]
Ah, thanks. You are da man!

File: R/tm_g_scatterplotmatrix.R [hunk 3]
```diff
@@ -15,27 +15,76 @@
 #'
 #' @note For more examples, please see the vignette "Using scatterplot matrix" via
 #'   \code{vignette("using-scatterplot-matrix", package = "teal.modules.general")}.
-#' @export
 #'
 #' @examples
-#' # Scatterplot matrix of variables from ADSL dataset
+# general data example
```
Comment (m7pr) [inline R/tm_g_scatterplotmatrix.R:20]:
```suggestion
#' general data example
```

**Review by m7pr — APPROVED** [review]
Hey, I can confirm all new examples run without issues. All modules, besides `tm_file_viewer` and `tm_front_page` have now a general example and CDISC example.

Well done. I do not have any other comment besides the one that gogonzo left. I also found one missing `'` backtick :P

File: R/tm_t_crosstable.R [hunk 4]
```diff
@@ -18,27 +18,72 @@
...
 #' @examples
-#' # Percentage cross table of variables from ADSL dataset
+#' # general data example
+#' library(teal.widgets)
+#'
+#' data <- teal_data()
+#' data <- within(data, {
+#'   CO2 <- CO2
+#'   CO2[["primary_key"]] <- seq_len(nrow(CO2))
+#' })
```
Comment (gogonzo) [inline R/tm_t_crosstable.R:29]: I suggest less correlated categorical variables. Previously used `mtcars` looks like better candidate. Then `x` could be all variables and `y` only factors 


```suggestion
#' data <- within(data, {
#'   library(nestcolor)
#'   mtcars <- mtcars
#'   for (v in c("cyl", "vs", "am", "gear")) {
#'     mtcars[[v]] <- as.factor(mtcars[[v]])
#'   }
#' })
```

Comment (chlebowa) [reply R/tm_t_crosstable.R]: `mtcars` it is :+1:

File: R/tm_g_scatterplotmatrix.R [hunk 5]
```diff
@@ -15,27 +15,76 @@
...
+#' data <- teal_data()
+#' data <- within(data, {
+#'   CO2_plants <- unique(data.frame(CO2[c("Plant", "Type", "Treatment")]))
+#'   CO2_results <- unique(data.frame(CO2[c("Plant", "conc", "uptake")]))
+#' })
```
[the remark this answers is not in the document]
Comment (gogonzo) [reply R/tm_g_scatterplotmatrix.R:25]: WDYT?

```r
sales <- data.frame(
  id = c(1, 2, 3, 4, 5),
  product_id = c(1, 2, 3, 1, 2),
  country = c("SWE", "SWE", "SWE", "PL", "PL"),
  quantity = c(10, 20, 30, 40, 50),
)

products <- data.frame(
  id = c(1, 2, 3),
  name = c("apple", "banana", "cherry"),
  cost = c(50, 100, 150),
  unit_price = c(100, 200, 300)
)
```

[the remark this answers is not in the document]
Comment (chlebowa) [reply R/tm_g_scatterplotmatrix.R:25]: It's a good start but it needs some work.

File: R/tm_g_scatterplotmatrix.R [hunk 6]
```diff
@@ -15,27 +15,107 @@
...
+#'             fixed = FALSE
+#'           )
+#'         ),
+#'         data_extract_spec(
+#'           dataname = "sales",
+#'           filter = filter_spec(
+#'             label = "Select variable:",
+#'             vars = "country_id",
+#'             choices = value_choices(data[["sales"]], "country_id"),
+#'             selected = c("DE", "FR"),
```
Comment (gogonzo) [inline R/tm_g_scatterplotmatrix.R:83]: It is possible that countries will filter row so that it will be n<10. I think you can select all on init or add more countries explicitly

Comment (chlebowa) [reply R/tm_g_scatterplotmatrix.R]: Done :+1:

**Review by gogonzo — APPROVED** [review]
👍

File: R/tm_variable_browser.R [hunk 7]
```diff
@@ -28,34 +28,55 @@
...
+#'   faithful <- faithful
+#'   CO2 <- CO2
+#' })
+#' datanames(data) <- c("iris", "mtcars", "women", "faithful", "CO2")
+#'
+#' app <- init(
+#'   data = data,
+#'   modules = modules(tm_variable_browser_module)
+#' )
+#' if (interactive()) {
```
Comment (kartikeyakirar) [inline R/tm_variable_browser.R:57]: there is error while running this example.
```
Listening on http://127.0.0.1:5675
[INFO] 2024-02-22 19:04:22.0670 pid:2104 token:[0b281f3f] teal Initializing reporter_previewer_module
Warning: Error in super$initialize: Assertion on 'label' failed: Must be of type 'character' (or 'NULL'), not 'list'.
  3: runApp
  2: print.shiny.appobj
  1: <Anonymous>
```

Comment (chlebowa) [reply R/tm_variable_browser.R:57]: https://github.com/insightsengineering/teal.modules.general/pull/651#issuecomment-1956677043

Comment (kartikeyakirar) [reply R/tm_variable_browser.R:57]: 🤦‍♂️ my bad

Comment (m7pr) [reply R/tm_variable_browser.R:57]: : p
