### PR TITLE
Store the user selections so our default selection logic can be applied

### LINKED ISSUE #682: [Bug]: Checkbox with label "Treat Variable as Factor" doesn't update
### What happened?

The dynamic behavior of the checkbox is not working as intended. The checkbox should be checked or unchecked based on the condition `unique_entries < 6`. However, it seems that the issue is caused by the condition `is.null(isolate(input$numeric_as_factor))` always being evaluated as FALSE after the initial assignment.

Check `mtcars$cyl (<6)`and` mtcars$hp (<30)`

sample code
```
library(teal.widgets)

# Module specification used in apps below
tm_variable_browser_module <- tm_variable_browser(
  label = "Variable browser",
  ggplot2_args = ggplot2_args(
    labs = list(subtitle = "Plot generated by Variable Browser Module")
  )
)

# general data example
data <- teal_data()
data <- within(data, {
  iris <- iris
  mtcars <- mtcars
  women <- women
  faithful <- faithful
  CO2 <- CO2
})
datanames(data) <- c("iris", "mtcars", "women", "faithful", "CO2")

app <- init(
  data = data,
  modules = modules(tm_variable_browser_module)
)
if (interactive()) {
  shinyApp(app$ui, app$server)
}
```

### sessionInfo()

_No response_

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

### PR DESCRIPTION
**Pull request by vedhav**
Closes #682

### CODE REVIEW

File: R/tm_variable_browser.R [hunk 1]
```diff
@@ -353,18 +355,27 @@ srv_variable_browser <- function(id,
...
           list(
             checkboxInput(
               session$ns("numeric_as_factor"),
               "Treat variable as factor",
-              value = `if`(
-                is.null(isolate(input$numeric_as_factor)),
-                unique_entries < .unique_records_default_as_factor,
-                isolate(input$numeric_as_factor)
-              )
+              value = get_default_choice()
```
Comment (kartikeyakirar) [inline R/tm_variable_browser.R:378]:
```suggestion
              value = `if` (
                is.null(varname_numeric_as_factor[[varname]]),
                unique_entries < .unique_records_default_as_factor,
                varname_numeric_as_factor[[varname]]
              )
```

How about this.

File: R/tm_variable_browser.R [hunk 2]
```diff
@@ -353,18 +355,27 @@ srv_variable_browser <- function(id,
...
       )
 
+      get_default_choice <- function() {
+        selected_variable <- plot_var$variable[[dataname]]
+        if (is.null(varname_numeric_as_factor[[selected_variable]])) {
+          length(unique(df[[selected_variable]])) < .unique_records_default_as_factor
+        } else {
+          varname_numeric_as_factor[[selected_variable]]
+        }
+      }
```
Comment (kartikeyakirar) [inline R/tm_variable_browser.R:365]:
```suggestion
     
```

**Review by kartikeyakirar — APPROVED** [review]
LGTM 👍
