### PR TITLE
Fix UI overlap in tm_g_distribution output panel (#896)

### LINKED ISSUE #896: UI Overlap
The changes make possible to open the app now with the devel version of all packages.

On the second app I see some UI overlap:

image

Note that there is a change on the manuals that is unrelated. Remove it and we can merge it.

_Originally posted by @llrs-roche in https://github.com/insightsengineering/teal.modules.general/pull/895#pullrequestreview-3019959959_

### PR DESCRIPTION
**Pull request by siddharthlokineni**
Wrap the tabsetPanel, Statistics Table, and Tests sections of ui_distribution in separate tags$div containers with top margins, so plot_with_settings_ui validation messages and h3 section headers no longer overlap when the plot area is empty.

# Pull Request

## Summary
- Wrap the tabsetPanel, Statistics Table, and Tests sections of `ui_distribution` in separate `tags$div` containers with 1rem top margins.
- Prevents the visual overlap reported in #896 where `plot_with_settings_ui` validation messages and `h3` section headers collided when the plot area had no rendered plot.
- Closes #896.

## Test plan
-  CI green (build, R CMD check, tests)
- Reviewer visually confirms the Statistics Table / Tests headers no longer overlap the histogram tab content using the reproducer code in #896
-  Existing "shinytest2" snapshots for `tm_g_distribution` still pass (or are refreshed if DOM-sensitive)

Fixes #896

### CODE REVIEW

**Comment by siddharthlokineni** [comment]
I have read the CLA Document and I hereby sign the CLA

File: R/tm_g_distribution.R [hunk 1]
```diff
@@ -241,24 +241,38 @@ ui_distribution <- function(id, ...) {
...
-      tabsetPanel(
-        id = ns("tabs"),
-        tabPanel("Histogram", teal.widgets::plot_with_settings_ui(id = ns("hist_plot"))),
-        tabPanel("QQplot", teal.widgets::plot_with_settings_ui(id = ns("qq_plot")))
+      tags$div(
+        tabsetPanel(
+          id = ns("tabs"),
+          tabPanel("Histogram", teal.widgets::plot_with_settings_ui(id = ns("hist_plot"))),
+          tabPanel("QQplot", teal.widgets::plot_with_settings_ui(id = ns("qq_plot")))
+        )
```
Comment (donyunardi) [inline R/tm_g_distribution.R]:
```suggestion
        tabsetPanel(
          id = ns("tabs"),
          tabPanel("Histogram", teal.widgets::plot_with_settings_ui(id = ns("hist_plot"))),
          tabPanel("QQplot", teal.widgets::plot_with_settings_ui(id = ns("qq_plot")))
```

We don't need to wrap tabsetPanel instead div, especially when there is no style assigned.

File: R/tm_g_distribution.R [hunk 2]
```diff
@@ -241,24 +241,38 @@ ui_distribution <- function(id, ...) {
...
-      conditionalPanel(
-        sprintf("input['%s'].length === 0", ns("dist_tests")),
-        div(
-          id = ns("please_select_a_test"),
-          "Please select a test"
+      tags$div(
+        style = "padding-top: 2rem;",
+        tags$h3("Statistics Table"),
+        tags$div(
+          style = "min-height: 120px; overflow: auto;",
```
Comment (donyunardi) [inline R/tm_g_distribution.R]:
```suggestion
          style = "min-height: 120px; position: relative;",
```

It feels safer with position approach. overflow can cause double scroll with DT.

**Review by donyunardi — CHANGES_REQUESTED** [review]
Thanks for submitting the PR! Please see my comments.

File: R/tm_g_distribution.R (hunk 2 above)
Comment (siddharthlokineni) [reply R/tm_g_distribution.R]: Agreed - position: relative is safer, no risk of nested scroll with DT. Applied and verified no double scrollbar on the Statistics Table. Force-pushed as 0f1ccfe.

File: R/tm_g_distribution.R (hunk 1 above)
Comment (siddharthlokineni) [reply R/tm_g_distribution.R]: Good catch - removed the unnecessary div wrapper. Pushed as 0f1ccfe.

**Comment by siddharthlokineni** [comment]
Thanks for the review @donyunardi  Both suggestions applied in 0f1ccfe:

1. Removed the unnecessary tags$div wrapper around tabsetPanel.
2. Switched the summary_table wrapper from overflow: auto to position: relative to avoid nested scroll with DT.

Verified locally in both empty and populated states - no regressions.

File: R/tm_g_distribution.R [hunk 3]
```diff
@@ -246,19 +246,31 @@ ui_distribution <- function(id, ...) {
...
+            div(
+              id = ns("please_select_a_test"),
+              "Please select a test"
+            )
+          ),
+          conditionalPanel(
+            sprintf("input['%s'].length > 0", ns("dist_tests")),
+            DT::dataTableOutput(ns("t_stats"))
+          )
+        )
```
Comment (donyunardi) [inline R/tm_g_distribution.R:267]:
```suggestion
      tags$div(
        style = "min-height: 120px; margin-top: 1rem",
        tags$h3("Statistics Table"),
        DT::dataTableOutput(ns("summary_table"))
      ),
      tags$div(
        style = "min-height: 120px;",
        tags$h3("Tests"),
        conditionalPanel(
          sprintf("input['%s'].length === 0", ns("dist_tests")),
          tags$div(
            id = ns("please_select_a_test"),
            "Please select a test"
          )
        ),
        conditionalPanel(
          sprintf("input['%s'].length > 0", ns("dist_tests")),
          DT::dataTableOutput(ns("t_stats"))
        )
      )
```

I think we can make it even simpler by taking your `min-height` idea to the top of the `div`. Then, we don't need the `position` style and second nested `div`.

What do you think?

**Review by donyunardi — CHANGES_REQUESTED** [review]

File: R/tm_g_distribution.R (hunk 3 above)
Comment (siddharthlokineni) [reply R/tm_g_distribution.R:267]: Thanks @donyunardi . Applied your simplification in a91fd172:

- Dropped the nested div + position: relative on the summary_table wrapper - the outer section's min-height is sufficient, as you said.
- Kept margin-top: 1rem on the Tests section too so both sections are styled symmetrically. Happy to drop it if you'd rather keep the Statistics Table as the sole spacer.

Verified locally in both empty and populated states.

**Review by donyunardi — APPROVED** [review]
LGTM!

Image

**Comment by siddharthlokineni** [comment]
Thanks for the quick review, @donyunardi. Happy to have contributed. You can assign me more issues if you feel i can help.
